version: 2

sphinx:
  configuration: pyslope/docs/conf.py

formats: all

python:
  version: 3.9
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
    - requirements: pyslope/docs/requirements_docs.txt

submodules:
  include: all