# Generated by Django 3.2.4 on 2022-03-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_weight", models.FloatField(default=20)),
                ("friction_angle", models.FloatField(default=35)),
                ("cohesion", models.FloatField(default=2)),
                ("depth_to_bottom", models.FloatField(default=5)),
                ("name", models.CharField(default="", max_length=50)),
                ("color", models.CharField(default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PointLoadModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("magnitude", models.FloatField(default=0)),
                ("offset", models.FloatField(default=0)),
                ("color", models.CharField(default="blue", max_length=20)),
                ("dynamic_offset", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SlopeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.FloatField(default=1)),
                ("angle", models.FloatField(default=30)),
                ("length", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UdlModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("magnitude", models.FloatField(default=0)),
                ("offset", models.FloatField(default=0)),
                ("length", models.FloatField(default=0)),
                ("color", models.CharField(default="red", max_length=20)),
                ("dynamic_offset", models.BooleanField(default=False)),
            ],
        ),
    ]
