# Generated by Django 3.2.4 on 2022-03-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slope", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialmodel",
            name="color",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="materialmodel",
            name="name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="pointloadmodel",
            name="color",
            field=models.CharField(blank=True, default="blue", max_length=20),
        ),
        migrations.AlterField(
            model_name="udlmodel",
            name="color",
            field=models.CharField(blank=True, default="red", max_length=20),
        ),
    ]
