# Generated by Django 3.2.5 on 2022-04-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slope", "0004_auto_20220329_1844"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialmodel",
            name="color",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="materialmodel",
            name="name",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
