# Generated by Django 3.2.5 on 2022-04-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slope", "0007_auto_20220411_0856"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialmodel",
            name="color",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
