# Generated by Django 3.2.4 on 2022-05-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slope", "0012_auto_20220423_2339"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PointLoadModel",
            new_name="LineLoadModel",
        ),
    ]
