# Generated by Django 5.0.3 on 2024-03-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slope', '0013_rename_pointloadmodel_lineloadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetainingWallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('thickness', models.FloatField(default=0.3)),
                ('unit_weight', models.FloatField(default=22)),
                ('angle', models.FloatField(default=90)),
            ],
        ),
    ]
