name: pre-commit

on: [pull_request, push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: x64
          cache: pip

      - name: Install pre-commit
        run: pip install --upgrade pip pre-commit

      - name: Run pre-commit hooks
        uses: pre-commit/action@v2
        with:
          extra_args: --all-files
          skip-automatic-cache: true  # avoids cache outage errors