name: Build Distribution

on: [push, pull_request]

jobs:
  test:
    runs-on : "ubuntu-latest"

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install build dependencies
        run: python -m pip install --upgrade pip build wheel

      - name: Build distributions
        run: python -m build --sdist --wheel

      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}